/*		App actions	 */
export const UPDATESTEP = 'UPDATESTEP';
export const NEXTEPISODE = 'NEXTEPISODE';
/* */

export const ADDTOMESSAGELIST = 'ADDTOMESSAGELIST';
export const UPDATEMESSAGELIST = 'UPDATEMESSAGELIST';
export const UPDATEMESSAGESTEP = 'UPDATEMESSAGESTEP';
export const UPDATEMESSAGEACTIVE = 'UPDATEMESSAGEACTIVE';
export const STARTMESSAGELIST = 'STARTMESSAGELIST';




/* conversation list */

export const UPDATECONVERSATIONLIST = 'UPDATECONVERSATIONLIST';
export const UPDATECONVERSATION = 'UPDATECONVERSATION';
export const ADDCONVOMESSAGE = 'ADDCONVOMESSAGE';
export const CREATECONVO = 'CREATECONVO';
/* */