/*		App actions	 */
export const UPDATESTEP = 'UPDATESTEP';

/* */

export const ADDTOMESSAGELIST = 'ADDTOMESSAGELIST';
export const UPDATEMESSAGELIST = 'UPDATEMESSAGELIST';
export const UPDATEMESSAGESTEP = 'UPDATEMESSAGESTEP';